POST http://127.0.0.1:8000/movies
Content-Type: application/json

{
  "title": "Inception",
  "year": 2010,
  "description": "A thief who steals corporate secrets through the use of dream-sharing technology.",
  "actors": [
    {"fullname": "Leonardo DiCaprio"},
    {"fullname": "Joseph Gordon-Levitt"}
  ]
}

###

GET http://127.0.0.1:8000/movies
Accept: application/json

###

GET http://127.0.0.1:8000/movies/1
Accept: application/json

###

PUT http://127.0.0.1:8000/movies/1
Content-Type: application/json

{
  "title": "Inception Updated",
  "year": 2010,
  "description": "Updated description.",
  "actors": [
    {"fullname": "Leonardo DiCaprio"},
    {"fullname": "Elliot Page"}
  ]
}

###

DELETE http://127.0.0.1:8000/movies/1
Accept: application/json

###

DELETE http://127.0.0.1:8000/movies
Accept: application/json